version: '3'
services:
  database:
    image: mariadb:11
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456g
      MYSQL_DATABASE: yourartistdb
      MYSQL_USER: yourartist
      MYSQL_PASSWORD: 123456g
    ports:
      - "3300:3306"